//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalidaMateriales.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string VersionSistema {
            get {
                return ((string)(this["VersionSistema"]));
            }
            set {
                this["VersionSistema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOLINO61\\CULTIVODES")]
        public string ServidorSQLMaestroEntidades {
            get {
                return ((string)(this["ServidorSQLMaestroEntidades"]));
            }
            set {
                this["ServidorSQLMaestroEntidades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MOLINO61\\CULTIVODES")]
        public string ServidorSQLCentral {
            get {
                return ((string)(this["ServidorSQLCentral"]));
            }
            set {
                this["ServidorSQLCentral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RutaProgramaAcceso {
            get {
                return ((string)(this["RutaProgramaAcceso"]));
            }
            set {
                this["RutaProgramaAcceso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b")]
        public string PrivilegioAccesoMenu {
            get {
                return ((string)(this["PrivilegioAccesoMenu"]));
            }
            set {
                this["PrivilegioAccesoMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivilegioAccesoFuncionalidad {
            get {
                return ((string)(this["PrivilegioAccesoFuncionalidad"]));
            }
            set {
                this["PrivilegioAccesoFuncionalidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("perfil")]
        public string Perfil {
            get {
                return ((string)(this["Perfil"]));
            }
            set {
                this["Perfil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NombreCorto {
            get {
                return ((string)(this["NombreCorto"]));
            }
            set {
                this["NombreCorto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Nombre {
            get {
                return ((string)(this["Nombre"]));
            }
            set {
                this["Nombre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vvalenzuela")]
        public string Login {
            get {
                return ((string)(this["Login"]));
            }
            set {
                this["Login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int IDSistema {
            get {
                return ((int)(this["IDSistema"]));
            }
            set {
                this["IDSistema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IDPerfil {
            get {
                return ((int)(this["IDPerfil"]));
            }
            set {
                this["IDPerfil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 230, 231")]
        public global::System.Drawing.Color ColorFondoSinFoco {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoSinFoco"]));
            }
            set {
                this["ColorFondoSinFoco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorFondoConFoco {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoConFoco"]));
            }
            set {
                this["ColorFondoConFoco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cargo {
            get {
                return ((string)(this["Cargo"]));
            }
            set {
                this["Cargo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaestroEntidades")]
        public string BaseSQLMaestroEntidades {
            get {
                return ((string)(this["BaseSQLMaestroEntidades"]));
            }
            set {
                this["BaseSQLMaestroEntidades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materiales_Prueba")]
        public string BaseSQLCentral {
            get {
                return ((string)(this["BaseSQLCentral"]));
            }
            set {
                this["BaseSQLCentral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Materiales_Prueba")]
        public string BaseDeDatosCentral {
            get {
                return ((string)(this["BaseDeDatosCentral"]));
            }
            set {
                this["BaseDeDatosCentral"] = value;
            }
        }
    }
}
